config/routes.rb
Skullweb::Application.routes.draw do
  resources :users, :user_sessions, :admins, :room
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
  match '/hj', :to => 'hj#index'
  match '/hj/completeJob', :to => 'hj#completeJob'
  match '/hj/weekChange', :to => 'hj#weekChange'
  match '/room', :to => 'room#index'
  match '/room/delete', :to => "room#delete"
  root :to => 'hj#index'
	

end

app/views/admin/account/forgot_password.html.erb
<%
  page_title = Typus::I18n.t("Forgot password")
  title(page_title)
%>

<%= form_for :typus_user, :url => { :action => :send_password } do |form| %>

  <ul>

    <li>
      <%= form.label :email, Typus.user_class.human_attribute_name(:email) %>
      <%= form.text_field :email, :size => 20, :class => "text", :autofocus => 'autofocus' %>
    </li>

    <li>
      <%= submit_tag Typus::I18n.t("Submit"), :class => "button", :disable_with => Typus::I18n.t("Sending data ...") %> <%= link_to Typus::I18n.t("I remember my password"), new_admin_session_path %>
    </li>

  </ul>

<% end %>

app/views/admin/account/new.html.erb
<%
  page_title = Typus::I18n.t("Sign up")
  title(page_title)
%>

<%= form_for :typus_user, :url => { :action => :create } do |form| %>

  <ul>

    <li>
      <%= form.label :email, Typus.user_class.human_attribute_name(:email) %>
      <%= form.text_field :email, :size => 20, :class => "text", :autofocus => 'autofocus' %>
    </li>

    <li>
      <%= submit_tag Typus::I18n.t("Sign up"), :class => "button", :disable_with => Typus::I18n.t("Sending data ...") %>
    </li>

  </ul>

<% end %>